### ISSUE TITLE
Eye pupils can be seen through the eyelids when characters are blinking

### ISSUE THREAD

**Issue by PiKeyAr** [ItsEasyActually/SA1_Chars#4] opened 2017-08-15 10:59 UTC
![image](https://user-images.githubusercontent.com/23312549/29313263-0e5fed0e-81f4-11e7-94d4-fc578a9c5687.png)
I originally assumed this was an anime style thing, but after a quick check this doesn't seem to happen in SA1. At least Sonic's talking head is affected, easy to see in the cutscenes before Perfect Chaos.

**Comment by ItsEasyActually** [comment] 2017-08-15 18:53
I was noticing this issue too, but I'm honestly not sure how to fix it. It's the models clipping through each other, so it's going to take some looking to figure out what's going on. I'm just hoping they didn't alter those event animations.

**Comment by PiKeyAr** [comment] 2017-08-24 14:41
I don't know much about this stuff, but it does seem like Sonic's pupils are sitting deeper in his eyes in SA1 or something? Maybe it's a morph thing.
Left is SADX, right is SA1
![e1](https://user-images.githubusercontent.com/23312549/29671841-7cd216d0-8925-11e7-8195-b67d1e6f0157.png)
![e2](https://user-images.githubusercontent.com/23312549/29671843-7cd6acae-8925-11e7-8f49-f3b2c9622725.png)
![e3](https://user-images.githubusercontent.com/23312549/29671842-7cd52e1a-8925-11e7-8b7d-da6bef04a09b.png)

**Comment by Mumu03** [comment] 2017-08-24 16:24
This might be the reason why that problem with Sonic's Eye exists.

**Comment by ItsEasyActually** [comment] 2017-08-24 16:47
This is the issue, and I thought I had resolved the problem by modifying the values for DX to be the same as DC, but I may not have gotten them correct. The alternate answer to the problem is that the animations were modified and are causing issues, though I doubt this is the case. 

_Sent from my Motorola XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SonicFreak94** [comment] 2017-08-24 20:20
If the animations were modified, moving the eyes in the node (`NJS_OBJECT`) hierarchy should resolve it anyway, so perhaps there's duplicate eye nodes?

**Comment by ItsEasyActually** [comment] 2017-08-24 23:14
I'm not able to check for accuracy atm, but IIRC, there's several (three or four) node objects in the hierarchy related to the eyes and their initial parent object. It's an identical count between the two games, however a lot of position and rotation values were changed for each of those nodes. I likely just got some values wrong and should be able to easily fix the issue.

_Sent from my Motorola XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ItsEasyActually** [comment] 2017-08-26 02:58
Solution was as simple as me literally forgetting to modify the models to their Dreamcast counterparts. I have no idea how that happened, but it's fixed now. The fix will be included in the next update.

**Closed by ItsEasyActually** 2017-08-26 02:58 UTC
