### ISSUE TITLE
Minor issues with MainMemory's Disable Upgrade Models mod 

### ISSUE THREAD

**Issue by Mumu03** [ItsEasyActually/SA1_Chars#2] opened 2017-08-14 19:10 UTC
This mod is mostly compatible with MainMemory's Disable Upgrade Models Mod, i suppose. I said mostly because some exclusive effects from this mod does not happen with the mod enabled and the upgrade models disabled. For example: Sonic's Normal Shoes doesn't stretch.

**Comment by ItsEasyActually** [comment] 2017-08-14 20:46
I have an idea as to why. You gave that as the only example, but is it the only instance of something missing?

_Sent from my Motorola XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mumu03** [comment] 2017-08-14 21:12
Tested it with everyone else, so yeah, that's definitively the only instance.

**Comment by ItsEasyActually** [comment] 2017-08-14 23:27
Alright, cool, I'll work on a fix for it. Thanks for the report!

_Sent from my Motorola XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ItsEasyActually** [comment] 2017-08-15 18:51
Alright, so I fixed this issue. It'll be in the next update I push for the mod.

**Comment by Mumu03** [comment] 2017-08-15 20:34
I just realized that there's a problem with Knuckles too. When i disable the Shovel Claw with that mod, it keeps the Fighting Glove's colors.

**Comment by ItsEasyActually** [comment] 2017-08-15 21:54
I have no idea what the problem is that you're talking about. Disabling the Shovel Claw only will retain the Fighting Gloves. They're two separate upgrades. 

Please provide some screenshots and what your config.ini in the DisableUpgrades mod looks like.

**Comment by Mumu03** [comment] 2017-08-15 22:21
Configurations:

DisableCrystalRing=True
DisableLightShoes=False
DisableJetAnklet=True
DisableRhythmBadge=False
DisableFightingGloves=True
DisableShovelClaw=False
DisableLongHammer=False
DisableWarriorFeather=True
DisableLaserBlaster=False
DisableJetBooster=False
DisablePowerRod=False
DisableLifeRing=False

Screenshots:

With Issues:
![20170815190830_1](https://user-images.githubusercontent.com/26584176/29339044-bfe98d42-81ee-11e7-8358-7685ae2a711b.jpg)

Without Issues:
![20170815191810_1](https://user-images.githubusercontent.com/26584176/29339054-c719e828-81ee-11e7-888a-8e95f7bbd77d.jpg)

The last screenshot in this comment had to use the BetterSADX exclusive Mimic DC Textures mod for obvious reasons.

**Comment by Mumu03** [comment] 2017-08-15 22:32
Welp, the worst part is, when i disable the Fighting Gloves Model and i enable the Shovel Claw Model again with that mod, it shows the same problem.

With Issues:
![20170815192623_1](https://user-images.githubusercontent.com/26584176/29339371-4e4a1fb0-81f0-11e7-9650-b870fc0beeb3.jpg)

Without Issues:
![20170815192810_1](https://user-images.githubusercontent.com/26584176/29339380-59f14582-81f0-11e7-9f90-ae8e583bfe3a.jpg)

Just like before, the last screenshot had to use the Mimic DC Textures mod.

**Comment by ItsEasyActually** [comment] 2017-08-15 23:03
Oh you know what, I believe this is an issue with that mod targeting the code for the upgrades, and I'm modifying Knuckles code for his models specifically. I'll see if I can figure up a work around with MainMemory to fix this issue.

**Comment by Mumu03** [comment] 2017-08-15 23:22
OK, Thanks.

**Comment by ItsEasyActually** [comment] 2017-08-16 00:25
Alright so this is gonna be a bit messier to fix actually, but it can be done. I just need an API to use for MainMemory's mod. Hopefully the next release will feature a fix for this, but if not, it'll come down the road. Thank you for the report on this issue though!

**Comment by ItsEasyActually** [comment] 2018-01-15 18:10
Update on this. It's been resolved. It'll be in the next update which should be out sometime soon.

**Closed as completed by ItsEasyActually** 2018-01-15 18:10 UTC
