### ISSUE TITLE
Sky Chase Cutscene Problem

### ISSUE THREAD

**Issue by sa-nd** [ItsEasyActually/SA1_Chars#28] opened 2019-07-15 00:37 UTC
There is an issue after completing sky chase act 2 in story mode as either character. The cutscene where the tornado 2 crash's into the egg carrier no longer works at all. The second the adventure field loading screen disappears the game crash's.  I checked to see which mods were active, and it's just this mod that crash's the game. Messing around with the configure settings didn't help.(Specifically, options relating to sky chase, the egg carrier, sonic, tails and the tornado.)  The cutscene only works when I disable this mod entirely. It doesn't seem to be an issue with the egg carrier adventure field, (Though it certainly could be!) because once the cutscene ends and the game saves, I reactivated the mod and everything worked fine. 

Hopefully this has a simple solution.

**Comment by PiKeyAr** [comment] 2019-07-19 05:18
According to **thespeedhighway**, this is caused by missing file EV_TR2CHANGE_WITH_SONIC.

**Comment by sa-nd** [comment] 2019-07-19 20:19
Thanks for the response!

EV_TR2CHANGE_WITH_SONIC.
Yep, that files missing here. 

Fortunately, I still have a copy of an older SA1 chars mod that I made just before I installed that one update that messed up Big's textures. I used it so I could replace Bigs glitched textures with the old ones, 
a temporary fix until it was properly patched. It still has the EV_TR2CHANGE_WITH_SONIC. file.
I put that in the current mods files and changed the file from a pvm file to a pvmx file and everything works fine now.

**Comment by PiKeyAr** [comment] 2019-07-20 02:40
I think the issue should be kept open until an update to the mod resolves this.

**Comment by ItsEasyActually** [comment] 2019-07-20 02:43
I'll have a fix for this in the coming days. I have no idea how I missed this file when doing the recent update.

**Comment by sa-nd** [comment] 2019-07-20 07:17
Sorry for closing it to begin with then, I assumed that the issue must have already been known and that a patch was probably coming soon for it. I jumped the gun a bit there.

**Comment by sa-nd** [comment] 2019-07-20 08:31
You're right PKR, it does make more sense to keep this open till this is patched.

**Comment by ItsEasyActually** [comment] 2019-07-28 23:04
Alright, it's been fixed. No new release, but the manifest has been updated. The ModManager should notify of the update being out.

**Closed as completed by ItsEasyActually** 2019-07-28 23:04 UTC
